### ISSUE TITLE
Parallelizable sumcheck project

### ISSUE THREAD

**Issue by krakhit** [ingonyama-zk/super-sumcheck#1]
```[tasklist]
### Tasks
- [ ] https://github.com/ingonyama-zk/gpu_sumcheck/issues/2
- [ ] https://github.com/ingonyama-zk/gpu_sumcheck/issues/3
- [ ] https://github.com/ingonyama-zk/gpu_sumcheck/issues/6
- [ ] https://github.com/ingonyama-zk/gpu_sumcheck/issues/5
- [ ] https://github.com/ingonyama-zk/gpu_sumcheck/issues/4
- [ ] https://github.com/ingonyama-zk/gpu_sumcheck/issues/7
- [ ] https://github.com/ingonyama-zk/gpu_sumcheck/issues/8
- [ ] https://github.com/ingonyama-zk/super-sumcheck/issues/16
```
